"""Pure-render insights panel cards built directly from deal state.

Nine of fourteen card kinds are derivable from structured state without an LLM.
This module produces those cards deterministically; the narrative three kinds
(`dealer_read`, `next_best_move`, `if_you_say_yes`) are still generated by the
panel LLM call. See `docs/haiku-panel-eval.md` (panel card audit) for the audit
that motivates this split.

Output cards are raw (pre-normalization) dicts shaped like the LLM's output:
`{kind, content, priority}`. Callers feed them through `normalize_panel_card`
plus `canonicalize_panel_cards` — the same pipeline the LLM cards use.
"""

from __future__ import annotations

from typing import Any

from app.models.enums import (
    NUMBER_HIGHLIGHT_VALUES,
    AiCardKind,
    AiCardPriority,
    DealPhase,
    NumberHighlight,
    VehicleRole,
)
from app.services.panel_cards import _NUMBER_FIELD_LABELS, GAP_PRIORITY_VALUES

_SHOPPING_VEHICLE_ROLES = {
    VehicleRole.PRIMARY.value,
    VehicleRole.CANDIDATE.value,
}

# Fields rendered in the numbers card, in display order.
_NUMBERS_DISPLAY_ORDER: tuple[str, ...] = (
    "msrp",
    "listing_price",
    "current_offer",
    "your_target",
    "walk_away_price",
    "trade_in_value",
    "down_payment",
    "monthly_payment",
    "apr",
    "loan_term_months",
    "invoice_price",
)

# Which scorecard subscore governs each deal-numbers field for highlight coloring.
_NUMBER_FIELD_SCORE_KEY: dict[str, str] = {
    "msrp": "price",
    "listing_price": "price",
    "current_offer": "price",
    "your_target": "price",
    "walk_away_price": "price",
    "invoice_price": "price",
    "monthly_payment": "financing",
    "apr": "financing",
    "loan_term_months": "financing",
    "down_payment": "financing",
    "trade_in_value": "trade_in",
}

_SCORE_TO_HIGHLIGHT: dict[str, str] = {
    "green": NumberHighlight.GOOD.value,
    "red": NumberHighlight.BAD.value,
    "yellow": NumberHighlight.NEUTRAL.value,
}

# High-mileage threshold: average annual miles above which we flag as risk.
_HIGH_MILES_PER_YEAR = 15_000

# Notes card cap (per schema: max 5).
_NOTES_MAX_ITEMS = 5

# Minimum dollar concession to surface as "savings so far" vs first offer.
_SAVINGS_SO_FAR_MIN_DELTA = 100


def build_rendered_panel_cards(deal_state_dict: dict[str, Any]) -> list[dict[str, Any]]:
    """Produce the render-only panel cards for this deal state.

    Returns a list of raw cards (pre-normalization). The synthesis cards
    (`dealer_read`, `next_best_move`, `if_you_say_yes`) are NOT included;
    the caller merges those from the LLM synthesis call.

    The `what_changed` card is not yet supported (needs a prior-numbers
    snapshot — deferred).
    """
    cards: list[dict[str, Any]] = []

    phase_card = _build_phase_card(deal_state_dict)
    if phase_card:
        cards.append(phase_card)

    cards.extend(_build_warning_cards(deal_state_dict))

    numbers_card = _build_numbers_card(deal_state_dict)
    if numbers_card:
        cards.append(numbers_card)

    leverage_card = _build_leverage_card(deal_state_dict)
    if leverage_card:
        cards.append(leverage_card)

    notes_card = _build_notes_card(deal_state_dict)
    if notes_card:
        cards.append(notes_card)

    cards.extend(_build_vehicle_cards(deal_state_dict))

    merged_checklist = _build_merged_checklist_card(deal_state_dict)
    if merged_checklist:
        cards.append(merged_checklist)

    savings_card = _build_savings_so_far_card(deal_state_dict)
    if savings_card:
        cards.append(savings_card)

    return cards


# ─── active-deal lookup ───


def _active_deal(deal_state_dict: dict[str, Any]) -> dict[str, Any] | None:
    deals = deal_state_dict.get("deals")
    if not isinstance(deals, list) or not deals:
        return None
    active_id = deal_state_dict.get("active_deal_id")
    if isinstance(active_id, str) and active_id:
        for deal in deals:
            if isinstance(deal, dict) and deal.get("id") == active_id:
                return deal
    # Fall back to the first deal if no active marker.
    first = deals[0]
    return first if isinstance(first, dict) else None


# ─── phase card ───


def _build_phase_card(deal_state_dict: dict[str, Any]) -> dict[str, Any] | None:
    context = deal_state_dict.get("negotiation_context")
    if not isinstance(context, dict):
        return None
    stance = context.get("stance")
    situation = context.get("situation")
    if not isinstance(stance, str) or not isinstance(situation, str):
        return None
    if not stance.strip() or not situation.strip():
        return None
    return {
        "kind": AiCardKind.PHASE.value,
        "content": {"stance": stance, "situation": situation},
        "priority": AiCardPriority.NORMAL.value,
    }


# ─── warning cards ───


def _build_warning_cards(
    deal_state_dict: dict[str, Any],
) -> list[dict[str, Any]]:
    # Combine deal-level + session-level red flags. Canonicalize caps to 1,
    # keeping the highest-priority one (critical before warning).
    raw_flags: list[dict[str, Any]] = []
    active = _active_deal(deal_state_dict)
    if active:
        deal_flags = active.get("red_flags")
        if isinstance(deal_flags, list):
            raw_flags.extend(flag for flag in deal_flags if isinstance(flag, dict))
    session_flags = deal_state_dict.get("session_red_flags")
    if isinstance(session_flags, list):
        raw_flags.extend(flag for flag in session_flags if isinstance(flag, dict))

    cards: list[dict[str, Any]] = []
    for flag in raw_flags:
        message = flag.get("message")
        if not isinstance(message, str) or not message.strip():
            continue
        severity = (
            flag.get("severity")
            if flag.get("severity") in {"critical", "warning"}
            else "warning"
        )
        priority = (
            AiCardPriority.CRITICAL.value
            if severity == "critical"
            else AiCardPriority.HIGH.value
        )
        cards.append(
            {
                "kind": AiCardKind.WARNING.value,
                "content": {"severity": severity, "message": message.strip()},
                "priority": priority,
            }
        )
    return cards


# ─── numbers card ───


def _build_numbers_card(
    deal_state_dict: dict[str, Any],
) -> dict[str, Any] | None:
    active = _active_deal(deal_state_dict)
    if not active:
        return None
    numbers = active.get("numbers")
    if not isinstance(numbers, dict):
        return None
    raw_scorecard = active.get("scorecard")
    scorecard: dict[str, Any] = raw_scorecard if isinstance(raw_scorecard, dict) else {}

    rows: list[dict[str, Any]] = []
    for field in _NUMBERS_DISPLAY_ORDER:
        value = numbers.get(field)
        if value is None:
            continue
        formatted = _format_number_value(field, value)
        if formatted is None:
            continue
        row: dict[str, Any] = {
            "label": _NUMBER_FIELD_LABELS.get(field, field.replace("_", " ").title()),
            "value": formatted,
            "field": field,
        }
        highlight = _highlight_for_field(field, scorecard)
        if highlight:
            row["highlight"] = highlight
        rows.append(row)

    # Append model-provided custom rows (doc fees, add-ons, tax, payoff, etc.).
    # These come from `update_deal_custom_numbers`; the model pre-formats the
    # `value` string so we just pass through after basic validation.
    custom_numbers = active.get("custom_numbers")
    if isinstance(custom_numbers, list):
        for raw in custom_numbers:
            if not isinstance(raw, dict):
                continue
            label = raw.get("label")
            value = raw.get("value")
            if not isinstance(label, str) or not label.strip():
                continue
            if not isinstance(value, str) or not value.strip():
                continue
            extra_row: dict[str, Any] = {
                "label": label.strip(),
                "value": value.strip(),
            }
            highlight = raw.get("highlight")
            if isinstance(highlight, str) and highlight in NUMBER_HIGHLIGHT_VALUES:
                extra_row["highlight"] = highlight
            rows.append(extra_row)

    if not rows:
        return None

    priority = _numbers_priority(active)
    return {
        "kind": AiCardKind.NUMBERS.value,
        "content": {"rows": rows},
        "priority": priority,
    }


def _numbers_priority(active_deal: dict[str, Any]) -> str:
    phase = active_deal.get("phase")
    if phase in {
        DealPhase.NEGOTIATION.value,
        DealPhase.FINANCING.value,
        DealPhase.CLOSING.value,
    }:
        return AiCardPriority.HIGH.value
    return AiCardPriority.NORMAL.value


def _format_number_value(field: str, value: Any) -> str | None:
    if field == "apr":
        try:
            return f"{float(value):.2f}%"
        except (TypeError, ValueError):
            return None
    if field == "loan_term_months":
        try:
            return f"{int(value)} mo"
        except (TypeError, ValueError):
            return None
    try:
        return f"${float(value):,.0f}"
    except (TypeError, ValueError):
        return None


def _highlight_for_field(field: str, scorecard: dict[str, Any]) -> str | None:
    score_key = _NUMBER_FIELD_SCORE_KEY.get(field)
    if not score_key:
        return None
    score = scorecard.get(score_key) if isinstance(scorecard, dict) else None
    if not isinstance(score, str):
        return None
    return _SCORE_TO_HIGHLIGHT.get(score)


# ─── your_leverage card ───


def _build_leverage_card(
    deal_state_dict: dict[str, Any],
) -> dict[str, Any] | None:
    context = deal_state_dict.get("negotiation_context")
    if not isinstance(context, dict):
        return None
    leverage = context.get("leverage")
    if not isinstance(leverage, list):
        return None
    bullets = [
        item.strip() for item in leverage if isinstance(item, str) and item.strip()
    ]
    if not bullets:
        return None
    # Card template expects `body` with optional `bullets`. Use the first item
    # as body and the rest as bullets so TIP template renders cleanly even
    # when there's only one leverage point.
    body = bullets[0]
    remaining = bullets[1:]
    content: dict[str, Any] = {"body": body}
    if remaining:
        content["bullets"] = remaining
    return {
        "kind": AiCardKind.YOUR_LEVERAGE.value,
        "content": content,
        "priority": AiCardPriority.NORMAL.value,
    }


# ─── notes card ───


def _build_notes_card(
    deal_state_dict: dict[str, Any],
) -> dict[str, Any] | None:
    items: list[str] = []

    # Notes must be durable KNOWN facts (dealer identity, offer history,
    # confirmed verbal commitments). Unknowns belong in the merged checklist
    # card's `open_questions`, not here — otherwise the card reads like a list of gaps.
    active = _active_deal(deal_state_dict)
    if active:
        dealer_name = active.get("dealer_name")
        if isinstance(dealer_name, str) and dealer_name.strip():
            items.append(f"Dealer: {dealer_name.strip()}")

        raw_numbers = active.get("numbers")
        numbers: dict[str, Any] = raw_numbers if isinstance(raw_numbers, dict) else {}
        current_offer_str = _format_money(numbers.get("current_offer"))

        offer_history = active.get("offer_history")
        if isinstance(offer_history, dict):
            first_offer_str = _format_money(offer_history.get("first_offer"))
            pre_fi_str = _format_money(offer_history.get("pre_fi_price"))
            # First offer: include only if the price has moved OR there's no
            # current offer yet. When no movement, the fact is redundant with
            # the numbers card.
            if first_offer_str and (
                (current_offer_str and current_offer_str != first_offer_str)
                or not current_offer_str
            ):
                items.append(f"First offer: {first_offer_str}")
            # Pre-F&I price only when it's meaningfully different from current.
            if pre_fi_str and pre_fi_str != current_offer_str:
                items.append(f"Pre-F&I price: {pre_fi_str}")

    if not items:
        return None

    return {
        "kind": AiCardKind.NOTES.value,
        "content": {"items": items[:_NOTES_MAX_ITEMS]},
        "priority": AiCardPriority.NORMAL.value,
    }


def _format_money(value: Any) -> str | None:
    if value is None:
        return None
    try:
        return f"${float(value):,.0f}"
    except (TypeError, ValueError):
        return None


def _iter_info_gaps(
    deal_state_dict: dict[str, Any],
    *,
    priority: str | None = None,
):
    def matches(gap: Any) -> bool:
        if not isinstance(gap, dict):
            return False
        if priority is None:
            return True
        return gap.get("priority") == priority

    active = _active_deal(deal_state_dict)
    if active:
        deal_gaps = active.get("information_gaps")
        if isinstance(deal_gaps, list):
            for gap in deal_gaps:
                if matches(gap):
                    yield gap
    session_gaps = deal_state_dict.get("session_information_gaps")
    if isinstance(session_gaps, list):
        for gap in session_gaps:
            if matches(gap):
                yield gap


# ─── vehicle cards ───


def _build_vehicle_cards(
    deal_state_dict: dict[str, Any],
) -> list[dict[str, Any]]:
    vehicles = deal_state_dict.get("vehicles")
    if not isinstance(vehicles, list):
        return []
    today_year = _current_year()
    cards: list[dict[str, Any]] = []
    for vehicle in vehicles:
        if not isinstance(vehicle, dict):
            continue
        role = vehicle.get("role")
        if role not in _SHOPPING_VEHICLE_ROLES and role != VehicleRole.TRADE_IN.value:
            continue
        make = vehicle.get("make")
        model = vehicle.get("model")
        if not (
            isinstance(make, str)
            and make.strip()
            and isinstance(model, str)
            and model.strip()
        ):
            continue

        vehicle_content: dict[str, Any] = {"make": make.strip(), "model": model.strip()}
        year = vehicle.get("year")
        if isinstance(year, int):
            vehicle_content["year"] = year
        for key in ("trim", "cab_style", "bed_length", "engine", "color", "vin"):
            raw = vehicle.get(key)
            if isinstance(raw, str) and raw.strip():
                vehicle_content[key] = raw.strip()
        mileage = vehicle.get("mileage")
        if isinstance(mileage, int) and mileage > 0:
            vehicle_content["mileage"] = mileage
        if isinstance(role, str) and role.strip():
            vehicle_content["role"] = role

        content: dict[str, Any] = {"vehicle": vehicle_content}
        risk_flags = _vehicle_risk_flags(
            mileage=mileage if isinstance(mileage, int) else None,
            year=year if isinstance(year, int) else None,
            today_year=today_year,
        )
        if risk_flags:
            content["risk_flags"] = risk_flags

        cards.append(
            {
                "kind": AiCardKind.VEHICLE.value,
                "content": content,
                "priority": AiCardPriority.NORMAL.value,
            }
        )
    return cards


def _vehicle_risk_flags(
    *, mileage: int | None, year: int | None, today_year: int
) -> list[str]:
    flags: list[str] = []
    if mileage and mileage > 0 and year and year <= today_year:
        age = max(1, today_year - year + 1)
        miles_per_year = mileage / age
        if miles_per_year >= _HIGH_MILES_PER_YEAR:
            flags.append(f"High mileage (~{int(miles_per_year):,} mi/yr)")
    return flags


def _current_year() -> int:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).year


# ─── merged checklist (playbook + open questions) ───


def _collect_open_question_rows(
    deal_state_dict: dict[str, Any],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for gap in _iter_info_gaps(deal_state_dict):
        label = gap.get("label")
        if not isinstance(label, str) or not label.strip():
            continue
        label_stripped = label.strip()
        if label_stripped in seen:
            continue
        seen.add(label_stripped)
        row: dict[str, Any] = {"label": label_stripped}
        priority = gap.get("priority")
        if priority in GAP_PRIORITY_VALUES:
            row["priority"] = priority
        rows.append(row)
    return rows


def _collect_checklist_playbook_rows(
    deal_state_dict: dict[str, Any],
) -> list[dict[str, Any]]:
    raw_items = deal_state_dict.get("checklist")
    if not isinstance(raw_items, list):
        return []
    items: list[dict[str, Any]] = []
    for raw in raw_items:
        if not isinstance(raw, dict):
            continue
        label = raw.get("label")
        if not isinstance(label, str) or not label.strip():
            continue
        items.append(
            {
                "label": label.strip(),
                "done": bool(raw.get("done", False)),
            }
        )
    return items


def _build_merged_checklist_card(
    deal_state_dict: dict[str, Any],
) -> dict[str, Any] | None:
    """Single checklist card: optional `open_questions` (gaps) + optional `items` (playbook).

    Merges only at panel render time; deal_state still stores gaps and checklist separately
    (update_deal_information_gaps / update_checklist). Builder dedupes overlapping labels only.
    """
    playbook = _collect_checklist_playbook_rows(deal_state_dict)
    playbook_labels_cf = {row["label"].casefold() for row in playbook}

    open_questions: list[dict[str, Any]] = []
    for row in _collect_open_question_rows(deal_state_dict):
        if row["label"].casefold() in playbook_labels_cf:
            continue
        open_questions.append(row)

    content: dict[str, Any] = {}
    if open_questions:
        content["open_questions"] = open_questions
    if playbook:
        content["items"] = playbook
    if not content:
        return None
    return {
        "kind": AiCardKind.CHECKLIST.value,
        "content": content,
        "priority": AiCardPriority.NORMAL.value,
    }


# ─── savings_so_far ───


def _build_savings_so_far_card(
    deal_state_dict: dict[str, Any],
) -> dict[str, Any] | None:
    active = _active_deal(deal_state_dict)
    if not active:
        return None
    numbers = active.get("numbers")
    if not isinstance(numbers, dict):
        return None
    offer_history = active.get("offer_history")
    first_offer = None
    if isinstance(offer_history, dict):
        first_offer = offer_history.get("first_offer")
    current_offer = numbers.get("current_offer")
    if first_offer is None or current_offer is None:
        return None
    try:
        delta = float(first_offer) - float(current_offer)
    except (TypeError, ValueError):
        return None
    # Only surface when meaningful (≥ $_SAVINGS_SO_FAR_MIN_DELTA concession).
    if delta < _SAVINGS_SO_FAR_MIN_DELTA:
        return None
    amount = f"${delta:,.0f}"
    return {
        "kind": AiCardKind.SAVINGS_SO_FAR.value,
        "content": {
            "headline": f"{amount} below first offer",
            "amount": amount,
            "body": (
                f"You've moved the dealer from {_format_money(first_offer)} "
                f"to {_format_money(current_offer)}."
            ),
        },
        "priority": AiCardPriority.NORMAL.value,
    }
