"""Post-chat processing — updates session metadata after a chat exchange.

Keeps the chat route thin by extracting preview and title update logic
into a single function called after tool calls are applied.
"""

import logging

from app.models.deal_state import DealState
from app.models.session import ChatSession
from app.services.title_generator import build_vehicle_title, generate_session_title

logger = logging.getLogger(__name__)

PREVIEW_MAX_LENGTH = 120
DEFAULT_BUYER_TITLE = "New Deal"
DEFAULT_DEALER_TITLE = "New Simulation"


def _truncate(text: str, max_length: int) -> str:
    """Truncate text to max_length, adding ellipsis if needed."""
    if len(text) <= max_length:
        return text
    return text[: max_length - 1] + "\u2026"


def _deal_state_to_vehicle_dict(deal_state: DealState | None) -> dict | None:
    """Extract vehicle info as a dict for title generation."""
    if deal_state is None or not deal_state.vehicle_make:
        return None
    return {
        "vehicle": {
            "year": deal_state.vehicle_year,
            "make": deal_state.vehicle_make,
            "model": deal_state.vehicle_model,
            "trim": deal_state.vehicle_trim,
        }
    }


def _update_preview(
    session: ChatSession,
    response_text: str,
    user_message: str,
) -> None:
    """Set last_message_preview from the assistant response or user message."""
    text = response_text.strip()
    if text:
        session.last_message_preview = _truncate(text, PREVIEW_MAX_LENGTH)
    elif user_message.strip():
        session.last_message_preview = _truncate(
            f"You: {user_message.strip()}", PREVIEW_MAX_LENGTH
        )


async def _update_title(
    session: ChatSession,
    deal_state: DealState | None,
    messages: list[dict],
    tool_calls: list[dict],
) -> None:
    """Update session title based on triggers. Only runs if auto_title is True."""
    if not session.auto_title:
        return

    vehicle_tool_called = any(tc["name"] == "set_vehicle" for tc in tool_calls)

    # Trigger 1: Vehicle was just set or updated — deterministic title
    if vehicle_tool_called:
        ds_dict = _deal_state_to_vehicle_dict(deal_state)
        if ds_dict:
            title = build_vehicle_title(ds_dict)
            if title:
                session.title = title
                logger.info(
                    "Title updated from vehicle: session_id=%s, title=%s",
                    session.id,
                    title,
                )
                return

    # Trigger 2: Title is still default after first AI response — LLM fallback
    if session.title in (DEFAULT_BUYER_TITLE, DEFAULT_DEALER_TITLE) and messages:
        title = await generate_session_title(messages)
        if title:
            session.title = title
            logger.info(
                "Title generated by LLM: session_id=%s, title=%s",
                session.id,
                title,
            )


async def update_session_metadata(
    session: ChatSession,
    deal_state: DealState | None,
    messages: list[dict],
    tool_calls: list[dict],
    response_text: str,
    user_message: str,
) -> None:
    """Update session preview and title after a chat exchange.

    Called from the chat route after tool calls are applied, before db.commit().
    """
    _update_preview(session, response_text, user_message)
    await _update_title(session, deal_state, messages, tool_calls)
